// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

export const MATCH_STARTED = 'MATCH_STARTED'
export const UPDATE_SCORE = 'UPDATE_SCORE'
export const UPDATE_SELECTED_MATCH = 'UPDATE_SELECTED_MATCH'
export const MATCH_STANDING = 'MATCH_STANDING'
export const LOADING_START = 'LOADING_START'
